#!/bin/bash

echo "=========================================="
echo "Alternative Methods to Get SHA-1"
echo "=========================================="
echo ""
echo "Your package name: com.example.one_clinic_app"
echo ""

echo "METHOD 1: Using Android Studio (Recommended)"
echo "=============================================="
echo "1. Open your project in Android Studio"
echo "2. Open Terminal in Android Studio (bottom panel)"
echo "3. Run: ./gradlew signingReport"
echo "4. Look for 'SHA1' under 'Variant: debug'"
echo ""

echo "METHOD 2: Using openssl (if Java doesn't work)"
echo "==============================================="
echo "Run this command:"
echo ""
echo "keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android | grep 'SHA1:'"
echo ""

echo "METHOD 3: Generate keystore if not exists"
echo "=========================================="
echo "If keystore doesn't exist, run your app first:"
echo ""
echo "cd /Users/murat/mobile_flutter"
echo "flutter run"
echo ""
echo "This will generate the debug keystore automatically."
echo ""

echo "METHOD 4: Use VS Code Extension"
echo "================================"
echo "1. Install 'Android Keystore Fingerprint' extension in VS Code"
echo "2. Open Command Palette (Cmd+Shift+P)"
echo "3. Type 'Android Keystore' and select the command"
echo ""

echo "METHOD 5: Use online tool"
echo "========================="
echo "Upload your keystore to:"
echo "https://tomeko.net/online_tools/hex_to_base64.php"
echo ""

echo "=========================================="
echo "After Getting SHA-1:"
echo "=========================================="
echo ""
echo "1. Go to: https://console.cloud.google.com"
echo "2. Select project: for-google-login"
echo "3. Go to: APIs & Services > Credentials"
echo "4. Click: CREATE CREDENTIALS > OAuth client ID"
echo "5. Choose: Android"
echo "6. Enter:"
echo "   - Name: One Clinic Android"
echo "   - Package: com.example.one_clinic_app"
echo "   - SHA-1: [your SHA-1 fingerprint]"
echo "7. Click: CREATE"
echo ""
echo "8. Create another credential:"
echo "   - Type: Web application"
echo "   - Name: One Clinic Web"
echo "   - Copy the Client ID"
echo ""
echo "9. Update lib/data/services/google_signin_config.dart"
echo "   with your Web Client ID"
echo ""
echo "10. Run: flutter clean && flutter run"
echo ""
